# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from collections.abc import Iterable, Iterator
from enum import StrEnum
from functools import cached_property
from typing import Any

from pydantic import BaseModel


class DataCheckStatus(StrEnum):
    COMPLETED = "completed"
    SKIPPED = "skipped"
    FAILED_TO_RUN = "failed_to_run"


class DataCheckWarning(BaseModel):
    """
    Represents a warning generated by a data check.

    Attributes:
        explain: Text description explaining the warning. It can contain things like
            field names, etc.
        field_names: List of fields for which the warning got triggered.
        context: Context of the warning, for programmatic use, can contain things like
            percent of values being not compliant, etc.
            The structure of this dictionary is decided by each check.
    """

    explain: str
    field_names: list[str] | None = None
    context: dict[str, Any] | None = None

    def violations_count(self) -> int:
        """
        Returns: Count of violations this warning describes.
            If the warning contains field names, this count is equal to number of
            fields. Otherwise, it's 1 (e.g. warning is created on the whole data).
        """
        if not self.field_names:
            return 1

        return len(self.field_names)


class DataCheckResult(BaseModel):
    """
    Result of running a check on a dataset.

    Attributes:
        check_id: Unique ID of a check.
        status: Status of running the check.
        warnings: Warnings this check generated.
        status_details: Additional information about status of the check (e.g. error
            message if status is FAILED_TO_RUN).
    """

    check_id: str
    status: DataCheckStatus
    warnings: tuple[DataCheckWarning, ...] = ()
    status_details: dict[str, Any] | None = None

    @classmethod
    def completed(cls, check_id: str, warnings: Iterable[DataCheckWarning]) -> DataCheckResult:
        return cls(
            check_id=check_id,
            status=DataCheckStatus.COMPLETED,
            warnings=tuple(warnings),
        )

    @classmethod
    def skipped(cls, check_id: str, reason: str) -> DataCheckResult:
        return cls(
            check_id=check_id,
            status=DataCheckStatus.SKIPPED,
            status_details={"reason": reason},
        )

    @classmethod
    def failed_to_run(cls, check_id: str, error: str) -> DataCheckResult:
        return cls(
            check_id=check_id,
            status=DataCheckStatus.FAILED_TO_RUN,
            status_details={"error_message": error},
        )

    def has_any_warnings(self) -> bool:
        return bool(self.warnings)


class DataCheckResults(BaseModel):
    elapsed_time_ms: int
    """
    How long (in milliseconds) did running checks take.
    """

    check_results: list[DataCheckResult]

    @cached_property
    def violation_count(self) -> int:
        """Returns: How many violations across all checks were reported."""
        return sum(w.violations_count() for w in self.warnings())

    def warnings(self) -> Iterator[DataCheckWarning]:
        """Returns: Iterator over all warnings from all checks."""
        for result in self.check_results:
            yield from result.warnings

    def safe_summary(self) -> dict[str, Any]:
        """Create a summary of data check results, which only contains high-level information."""
        return {
            "violation_count": self.violation_count,
            "duration_ms": self.elapsed_time_ms,
            "warnings": {
                # only report check_id, no info about actual dataset
                result.check_id: {"count": sum(w.violations_count() for w in result.warnings)}
                for result in self.check_results
                if result.has_any_warnings()
            },
        }
