# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

training:
  batch_size: 4
  gradient_accumulation_steps: 16
  pretrained_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
privacy:
  dp_enabled: true
generation:
  structured_generation:
    enabled: true
  num_records: 3000
