default_install_hook_types: [pre-commit, commit-msg, pre-push]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        args:
          - --assume-in-merge

      # todo: re-enable after we're cleanly off of NMP since 
      # this is more invasive there
      # - id: end-of-file-fixer
      #   files: ".*\\.(py|sh|toml|yaml|yml|md|rst|txt)$"

      # - id: trailing-whitespace
      #   files: ".*\\.(py|sh|toml|yaml|yml|md|rst|txt)$"

      - id: check-merge-conflict
        args:
          - --assume-in-merge


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ".*\\.ipynb$"
      - id: ruff-check
        args: [--select, 'I', --fix]
        exclude: ".*\\.ipynb$"
      # Run the formatter.
      - id: ruff-format
        exclude: ".*\\.ipynb$"

  - repo: local
    hooks:
      - id: copyright-fix
        name: Fix copyright headers
        entry: uv run --script tools/lint/copyright_fixer.py .
        language: system
        pass_filenames: false
        files: '\.(py|sh|md|yaml|yml)$'

      - id: ty
        name: Run ty typechecks
        entry: bash tools/lint/run-ty-check.sh
        language: system
        pass_filenames: false
        types: [python]

      - id: uv-lock
        name: Run uv lock and check for uv.lock drift
        entry: bash -c 'uv lock && git diff --exit-code uv.lock'
        language: system
        files: 'pyproject\.toml$'
        pass_filenames: false
        verbose: true

      - id: check-signoff
        name: Check commit is signed off (DCO)
        entry: "grep -qE '^Signed-off-by: .+ <.+>'"
        language: system
        stages: [commit-msg]
        always_run: true
