#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#MISE description="Build wheel (version from git tag via uv-dynamic-versioning)"

set -euo pipefail

echo "~~~~~~"
rm -rf dist/
uv build --wheel
echo "wheel built: $(ls dist/*.whl)"
