# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

data:
  group_training_examples_by: null
  holdout: 0.05
  max_holdout: 2000
  max_sequences_per_example: null
  order_training_examples_by: null
  random_state: 329896
enable_replace_pii: true
evaluation:
  aia_enabled: true
  enabled: true
  mandatory_columns: null
  mia_enabled: true
  pii_replay_columns: null
  pii_replay_enabled: true
  pii_replay_entities: null
  quasi_identifier_count: 3
  sqs_report_columns: 250
  sqs_report_rows: 5000
generation:
  invalid_fraction_threshold: 0.8
  num_records: 1000
  patience: 1
  repetition_penalty: 1.0
  temperature: 0.9
  top_p: 1.0
  use_structured_generation: true
  guided_decoding_backend: guidance
privacy:
  delta: auto
  dp_enabled: true
  epsilon: 1.0
  per_sample_max_grad_norm: 1.0
training:
  batch_size: 1
  gradient_accumulation_steps: 8
  learning_rate: 0.0005
  lora_alpha_over_r: 1.0
  lora_r: 32
  lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  lr_scheduler: cosine
  num_input_records_to_sample: 25000
  pretrained_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
  rope_scaling_factor: auto
  use_unsloth: auto
  validation_ratio: 0.0
  validation_steps: 15
  warmup_ratio: 0.05
  weight_decay: 0.01
