# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Processors that parse raw LLM text into validated records."""

from __future__ import annotations

import functools
from abc import ABC, abstractmethod
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from ..config import SafeSynthesizerParameters
from ..config.generate import ValidationParameters
from ..data_processing.record_utils import (
    ExtractionResult,
    check_if_records_are_ordered,
    extract_and_validate_records,
    extract_and_validate_timeseries_records,
    extract_groups_from_jsonl_string,
)
from ..llm.metadata import ModelMetadata
from ..observability import get_logger

if TYPE_CHECKING:
    from transformers import PreTrainedTokenizerBase

logger = get_logger(__name__)


@dataclass
class ParsedResponse:
    """Parsed result of a single LLM prompt response.

    Token count lists are parallel to ``valid_records`` and ``invalid_records``
    so that counts follow records through reclassification (group-level rejection,
    data-fidelity checks).  Empty when no tokenizer is provided.

    Attributes:
        valid_records: Records that passed schema validation (as dicts).
        invalid_records: Raw text of records that failed validation.
        errors: ``(detailed_msg, summary_msg)`` tuples for each invalid
            record.
        prompt_number: Index of the prompt in the batch.
        valid_record_token_counts: Token count per valid record (parallel
            to ``valid_records``).
        invalid_record_token_counts: Token count per invalid record
            (parallel to ``invalid_records``).
        tokenization_time_sec: Wall-clock seconds spent tokenizing
            records in this response.
    """

    valid_records: list[dict]
    invalid_records: list[str]
    errors: list[tuple[str, str]]
    prompt_number: int | None = None
    valid_record_token_counts: list[int] = field(default_factory=list)
    invalid_record_token_counts: list[int] = field(default_factory=list)
    tokenization_time_sec: float = 0.0


class Processor(ABC):
    """Abstract class for processing text generation results from the LLM.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters.
        tokenizer: Optional tokenizer for exact token counting during
            record parsing.  When ``None``, token counts are not tracked.
    """

    def __init__(
        self,
        schema: dict[str, Any],
        config: ValidationParameters,
        tokenizer: PreTrainedTokenizerBase | None = None,
    ):
        self.schema = schema
        self.config = config
        self._tokenizer = tokenizer
        logger.debug(f"Initialized processor with schema={schema} and config={config}")

    @property
    def _encode(self) -> Callable[[str], list[int]] | None:
        """Tokenizer encode callable with ``add_special_tokens=False``, or ``None``."""
        if self._tokenizer is None:
            return None
        return functools.partial(self._tokenizer.encode, add_special_tokens=False)

    @property
    def name(self) -> str:
        """The processor's name with spaces, for logging."""
        n = self.__class__.__name__
        return n[0] + "".join(" " + c if c.isupper() else c for c in n[1:])

    @abstractmethod
    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the LLM.

        All subclasses must implement this method. This method is responsible
        for extracting and validating records from a single string of text,
        which must be returned as a ParsedResponse object.

        Args:
            text: Text generated by the LLM.

        Returns:
            Parsed response object that contains the extracted records.
        """
        ...

    def __call__(self, prompt_number: int, text: str) -> ParsedResponse:
        """Parse a single LLM response into validated records.

        Sanitizes the text to valid UTF-8, delegates to the subclass
        ``_process_text_generation`` implementation, and tags the result
        with ``prompt_number``.

        Args:
            prompt_number: Index of the prompt within the current batch.
            text: Raw text generated by the fine-tuned model.

        Returns:
            Parsed response containing valid records, invalid records,
            and error tuples.
        """
        # Make sure the string composed of valid utf-8 characters.
        text = text.encode("utf-8", "ignore").decode("utf-8")

        # Call the processor-specific method to process the text.
        response = self._process_text_generation(text)
        response.prompt_number = prompt_number

        return response


class TabularDataProcessor(Processor):
    """Processor for standard (non-grouped, non-time-series) tabular data."""

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Extract and validate records from a flat JSONL string.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response with validated records and error details.
        """
        result = extract_and_validate_records(text, self.schema, encode=self._encode)
        return _extraction_result_to_parsed_response(result)


class TimeSeriesDataProcessor(Processor):
    """Processor for time-series data generation tasks.

    Validates chronological ordering and timestamp intervals in
    addition to the standard schema checks.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters.
        time_column: Name of the timestamp column.
        interval_seconds: Expected interval between consecutive
            timestamps, or ``None`` if intervals vary.
        time_format: Timestamp format string (``strptime``), or
            ``"elapsed_seconds"`` for numeric elapsed time.

    Raises:
        ValueError: If ``time_column`` or ``time_format`` is ``None``.
    """

    def __init__(
        self,
        schema: dict[str, Any],
        config: ValidationParameters,
        time_column: str | None,
        interval_seconds: int | None,
        time_format: str | None,
        tokenizer: PreTrainedTokenizerBase | None = None,
    ):
        super().__init__(schema=schema, config=config, tokenizer=tokenizer)
        if time_column is None:
            raise ValueError(
                "time_column is required for TimeSeriesDataProcessor but was None. "
                "Ensure config.time_series.timestamp_column is set."
            )
        if time_format is None:
            raise ValueError(
                "time_format is required for TimeSeriesDataProcessor but was None. "
                "This should have been inferred during training preprocessing. "
                "Check that process_timeseries_data() was called during training and "
                "that the inferred timestamp_format was saved to the config."
            )
        self.time_column: str = time_column
        self.interval_seconds = interval_seconds
        self.time_format: str = time_format

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Extract, validate, and check temporal ordering of time-series records.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response with validated records and error details.
        """
        result = extract_and_validate_timeseries_records(
            text, self.schema, self.time_column, self.interval_seconds, self.time_format,
            encode=self._encode,
        )
        return _extraction_result_to_parsed_response(result)


class GroupedDataProcessor(Processor):
    """Processor for grouped data generation tasks.

    Used when training examples are grouped (and optionally ordered) by
    a column.  Validates that each group has a unique ``group_by`` value
    and respects the ``order_by`` ordering.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters controlling tolerance for
            invalid records, non-unique group values, etc.
        bos_token: Token delimiting the beginning of a group sequence.
        eos_token: Token delimiting the end of a group sequence.
        group_by: Column name that defines groups.
        order_by: Column name to enforce ordering within a group, or
            ``None`` if ordering is not required.
    """

    def __init__(
        self,
        schema: dict[str, Any],
        config: ValidationParameters,
        bos_token: str,
        eos_token: str,
        group_by: str,
        order_by: str | None = None,
        tokenizer: PreTrainedTokenizerBase | None = None,
    ):
        super().__init__(schema=schema, config=config, tokenizer=tokenizer)
        self.group_by: list[str] = [group_by]
        self.order_by = order_by
        self.bos_token = bos_token
        self.eos_token = eos_token

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the fine-tuned model.

        For records to be valid, they should:
            - Be in a group that is bound by BOS and EOS tokens.
            - Respect the known JSONL schema.
            - Have a unique value for the `group_by` field(s).
            - Be ordered by the `order_by` field if specified.

        These requirements may be relaxed and automatically fixed depending on
        the settings in self.config.

        When a tokenizer is available, per-record token counts are tracked
        through group-level reclassification so that ``valid_record_token_counts``
        always corresponds to the final ``valid_records``.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response object that contains the extracted records.
        """
        groups = extract_groups_from_jsonl_string(text, self.bos_token, self.eos_token)
        groupby_validator = "groupby"

        if len(groups) == 0 and self.config.group_by_accept_no_delineator:
            groups = [text]

        if len(groups) == 0:
            return ParsedResponse(
                valid_records=[],
                invalid_records=[text],
                errors=[("Group BOS and/or EOS tokens missing", groupby_validator)],
            )

        all_valid_records: list[dict] = []
        all_invalid_records: list[str] = []
        all_errors: list[tuple[str, str]] = []
        all_valid_token_counts: list[int] = []
        all_invalid_token_counts: list[int] = []
        total_tokenization_time = 0.0

        for group in groups:
            result = extract_and_validate_records(group, self.schema, encode=self._encode)
            total_tokenization_time += result.tokenization_time_sec

            valid_records = list(result.valid_records)
            invalid_records = list(result.invalid_records)
            errors = list(result.errors)
            valid_token_counts = list(result.valid_record_token_counts)
            invalid_token_counts = list(result.invalid_record_token_counts)

            # Handle invalid records in the group (optionally ignore and proceed).
            if valid_records and invalid_records:
                if self.config.group_by_ignore_invalid_records:
                    invalid_records = []
                    errors = []
                    invalid_token_counts = []
                else:
                    _reject_group_records(
                        valid_records, invalid_records, errors,
                        valid_token_counts, invalid_token_counts,
                        ("Invalid JSON in other groupby records", groupby_validator),
                    )

            # Handle non-unique group_by values (optionally fix by using first record's values).
            if valid_records and len(set(tuple(record[gb] for gb in self.group_by) for record in valid_records)) != 1:
                if self.config.group_by_fix_non_unique_value:
                    for group_by in self.group_by:
                        for record in valid_records[1:]:
                            record[group_by] = valid_records[0][group_by]
                else:
                    _reject_group_records(
                        valid_records, invalid_records, errors,
                        valid_token_counts, invalid_token_counts,
                        ("Groupby value is not unique", groupby_validator),
                    )

            # Handle unordered records when order_by is set (optionally fix by sorting).
            if valid_records and self.order_by is not None and not check_if_records_are_ordered(valid_records, self.order_by):
                if self.config.group_by_fix_unordered_records:
                    valid_records.sort(key=lambda x: x[self.order_by])
                else:
                    _reject_group_records(
                        valid_records, invalid_records, errors,
                        valid_token_counts, invalid_token_counts,
                        ("Group not ordered", groupby_validator),
                    )

            all_valid_records.extend(valid_records)
            all_invalid_records.extend(invalid_records)
            all_errors.extend(errors)
            all_valid_token_counts.extend(valid_token_counts)
            all_invalid_token_counts.extend(invalid_token_counts)

        return ParsedResponse(
            valid_records=all_valid_records,
            invalid_records=all_invalid_records,
            errors=all_errors,
            valid_record_token_counts=all_valid_token_counts,
            invalid_record_token_counts=all_invalid_token_counts,
            tokenization_time_sec=total_tokenization_time,
        )


def _reject_group_records(
    valid_records: list[dict],
    invalid_records: list[str],
    errors: list[tuple[str, str]],
    valid_token_counts: list[int],
    invalid_token_counts: list[int],
    error: tuple[str, str],
) -> None:
    """Reclassify all valid records as invalid (in-place).

    Moves every valid record into the invalid list (as its string
    representation), appends *error* once per moved record, shifts
    the corresponding token counts, and clears the valid lists.
    After this call ``valid_records`` is empty, which causes
    downstream ``if valid_records:`` guards to short-circuit.
    """
    n_valid = len(valid_records)
    valid_as_strings = [str(r) for r in valid_records]
    invalid_records[:] = valid_as_strings + invalid_records
    errors[:] = errors + [error] * n_valid
    invalid_token_counts[:] = valid_token_counts + invalid_token_counts
    valid_records.clear()
    valid_token_counts.clear()


def _extraction_result_to_parsed_response(result: ExtractionResult) -> ParsedResponse:
    """Convert an ``ExtractionResult`` into a ``ParsedResponse``."""
    return ParsedResponse(
        valid_records=result.valid_records,
        invalid_records=result.invalid_records,
        errors=result.errors,
        valid_record_token_counts=result.valid_record_token_counts,
        invalid_record_token_counts=result.invalid_record_token_counts,
        tokenization_time_sec=result.tokenization_time_sec,
    )


def create_processor(
    schema: dict[str, Any],
    metadata: ModelMetadata,
    config: SafeSynthesizerParameters,
    tokenizer: PreTrainedTokenizerBase | None = None,
) -> Processor:
    """Create the appropriate record processor for the current pipeline mode.

    Selects ``TimeSeriesDataProcessor``, ``GroupedDataProcessor``, or
    ``TabularDataProcessor`` based on the pipeline configuration.

    Args:
        schema: JSON schema describing the expected record format.
        metadata: Model metadata (prompt template, BOS/EOS tokens, etc.).
        config: Pipeline configuration determining the generation mode.
        tokenizer: Optional tokenizer for exact token counting during
            record parsing.  When ``None``, token counts are not tracked.

    Returns:
        Processor instance matching the configured generation mode.
    """
    if config.time_series.is_timeseries:
        processor = TimeSeriesDataProcessor(
            schema,
            config=config.generation.validation,
            time_column=config.time_series.timestamp_column,
            interval_seconds=config.time_series.timestamp_interval_seconds,
            time_format=config.time_series.timestamp_format,
            tokenizer=tokenizer,
        )
    elif config.data.group_training_examples_by:
        processor = GroupedDataProcessor(
            schema,
            config=config.generation.validation,
            group_by=config.data.group_training_examples_by,
            order_by=config.data.order_training_examples_by,
            bos_token=metadata.prompt_config.bos_token,
            eos_token=metadata.prompt_config.eos_token,
            tokenizer=tokenizer,
        )
    else:
        processor = TabularDataProcessor(schema, config=config.generation.validation, tokenizer=tokenizer)

    logger.info(f"Initialized the {processor.name}")
    return processor
