# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

from ..config import SafeSynthesizerParameters
from ..data_processing.record_utils import (
    check_if_records_are_ordered,
    extract_and_validate_records,
    extract_and_validate_timeseries_records,
    extract_groups_from_jsonl_string,
)
from ..llm.metadata import ModelMetadata
from ..observability import get_logger

logger = get_logger(__name__)


@dataclass
class ParsedResponse:
    """Dataclass to store the parsed response to a single prompt."""

    valid_records: list[dict]
    invalid_records: list[str]
    errors: list[tuple[str, str]]
    prompt_number: int | None = None


class Processor(ABC):
    """Abstract class for processing text generation results from the LLM.

    Args:
        schema: JSON schema as a dictionary.
    """

    def __init__(self, schema: dict):
        self.schema = schema

    @property
    def name(self):
        """Return the processor's name with spaces for logging."""
        n = self.__class__.__name__
        return n[0] + "".join(" " + c if c.isupper() else c for c in n[1:])

    @abstractmethod
    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the LLM.

        All subclasses must implement this method. This method is responsible
        for extracting and validating records from a single string of text,
        which must be returned as a ParsedResponse object.

        Args:
            text: Text generated by the LLM.

        Returns:
            Parsed response object that contains the extracted records.
        """
        ...

    def __call__(self, prompt_number: int, text: str) -> ParsedResponse:
        """Wraps the process_text_generation method.

        Call method that is meant to be the entrypoint for all processors
        during the generation process. This method ensures that the text is
        properly encoded and decoded before calling the processor-specific method.

        Args:
            prompt_number: Prompt number associated with the text provided
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response object that contains the extracted records.
        """

        # Make sure the string composed of valid utf-8 characters.
        text = text.encode("utf-8", "ignore").decode("utf-8")

        # Call the processor-specific method to process the text.
        response = self._process_text_generation(text)
        response.prompt_number = prompt_number

        return response


class TabularDataProcessor(Processor):
    """Processor for standard tabular data generation tasks."""

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the fine-tuned model.

        Args:
            text: Text generated by the fine-tuned model.
        """
        valid, invalid, errors = extract_and_validate_records(text, self.schema)
        return ParsedResponse(valid_records=valid, invalid_records=invalid, errors=errors)


class TimeSeriesDataProcessor(Processor):
    """Processor for time-series data generation tasks."""

    def __init__(self, schema: dict, time_column: str | None, interval_seconds: int | None, time_format: str | None):
        super().__init__(schema=schema)
        if time_column is None:
            raise ValueError(
                "time_column is required for TimeSeriesDataProcessor but was None. "
                "Ensure config.time_series.timestamp_column is set."
            )
        if time_format is None:
            raise ValueError(
                "time_format is required for TimeSeriesDataProcessor but was None. "
                "This should have been inferred during training preprocessing. "
                "Check that process_timeseries_data() was called during training and "
                "that the inferred timestamp_format was saved to the config."
            )
        self.time_column: str = time_column
        self.interval_seconds = interval_seconds
        self.time_format: str = time_format

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the fine-tuned model.

        Args:
            text: Text generated by the fine-tuned model.
        """
        valid, invalid, errors = extract_and_validate_timeseries_records(
            text, self.schema, self.time_column, self.interval_seconds, self.time_format
        )
        return ParsedResponse(valid_records=valid, invalid_records=invalid, errors=errors)


class GroupedDataProcessor(Processor):
    """Processor for grouped data generation tasks.

    This processor is used when the training examples are grouped
    (and optionally ordered) by a column or columns.
    """

    def __init__(
        self,
        schema: dict,
        bos_token: str,
        eos_token: str,
        group_by: str | list[str],
        order_by: str | None = None,
    ):
        super().__init__(schema=schema)
        if isinstance(group_by, str):
            group_by = [group_by]
        self.group_by = group_by
        self.order_by = order_by
        self.bos_token = bos_token
        self.eos_token = eos_token

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the fine-tuned model.

        For records to be valid, they must:
            - Be in a group that is bound by BOS and EOS tokens.
            - Respect the known JSONL schema.
            - Have a unique value for the `group_by` field(s).
            - Be ordered by the `order_by` field if specified.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response object that contains the extracted records.
        """
        groups = extract_groups_from_jsonl_string(text, self.bos_token, self.eos_token)
        groupby_validator = "groupby"

        if len(groups) == 0:
            return ParsedResponse(
                valid_records=[],
                invalid_records=[text],
                errors=[("Group BOS and/or EOS tokens missing", groupby_validator)],
            )

        valid_groups, invalid_groups, errors_groups = [], [], []

        for group in groups:
            valid, invalid, errors = extract_and_validate_records(group, self.schema)
            valid_with_str_members = [str(item) for item in valid]

            # If there are any invalid records, the entire group is invalid.
            if len(invalid) > 0:
                invalid = valid_with_str_members + invalid
                errors = errors + [("Invalid JSON in other groupby records", groupby_validator)] * len(valid)
                valid = []

            # The group is invalid if the set of group_by fields is not unique.
            elif len(set([tuple(record[group_by] for group_by in self.group_by) for record in valid])) != 1:
                valid, invalid = [], valid_with_str_members + invalid
                errors = [("Groupby value is not unique", groupby_validator)] * len(invalid)

            # If order_by is specified, the group is invalid if the records are not ordered.
            elif self.order_by is not None and not check_if_records_are_ordered(valid, self.order_by):
                valid, invalid = [], valid_with_str_members + invalid
                errors = [("Group not ordered", groupby_validator)] * len(invalid)

            valid_groups.extend(valid)
            invalid_groups.extend(invalid)
            errors_groups.extend(errors)

        return ParsedResponse(
            valid_records=valid_groups,
            invalid_records=invalid_groups,
            errors=errors_groups,
        )


def create_processor(schema: dict, metadata: ModelMetadata, config: SafeSynthesizerParameters) -> Processor:
    """Helper function for creating the appropriate processor.

    Args:
        schema: JSON schema as a dictionary.
        metadata: Internal training configuration.
        config: SafeSynthesizerParameters configuration.

    Returns:
        The appropriate processor based on the given model_metadata.
    """
    if config.time_series.is_timeseries:
        processor = TimeSeriesDataProcessor(
            schema,
            time_column=config.time_series.timestamp_column,
            interval_seconds=config.time_series.timestamp_interval_seconds,
            time_format=config.time_series.timestamp_format,
        )
    elif config.data.group_training_examples_by:
        processor = GroupedDataProcessor(
            schema,
            group_by=config.data.group_training_examples_by,
            order_by=config.data.order_training_examples_by,
            bos_token=metadata.prompt_config.bos_token,
            eos_token=metadata.prompt_config.eos_token,
        )
    else:
        processor = TabularDataProcessor(schema)

    logger.info(f"Initialized the {processor.name}")
    return processor
