# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Processors that parse raw LLM text into validated records."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

from ..config import SafeSynthesizerParameters
from ..config.generate import ValidationParameters
from ..data_processing.record_utils import (
    check_if_records_are_ordered,
    extract_and_validate_records,
    extract_and_validate_timeseries_records,
    extract_groups_from_jsonl_string,
)
from ..llm.metadata import ModelMetadata
from ..observability import get_logger

logger = get_logger(__name__)


@dataclass
class ParsedResponse:
    """Parsed result of a single LLM prompt response.

    Attributes:
        valid_records: Records that passed schema validation (as dicts).
        invalid_records: Raw text of records that failed validation.
        errors: ``(detailed_msg, summary_msg)`` tuples for each invalid
            record.
        prompt_number: Index of the prompt in the batch.
    """

    valid_records: list[dict]
    invalid_records: list[str]
    errors: list[tuple[str, str]]
    prompt_number: int | None = None


class Processor(ABC):
    """Abstract class for processing text generation results from the LLM.

    Args:
        schema: JSON schema as a dictionary.
    """

    def __init__(self, schema: dict, config: ValidationParameters):
        self.schema = schema
        self.config = config
        logger.debug(f"Initialized processor with schema={schema} and config={config}")

    @property
    def name(self):
        """The processor's name with spaces, for logging."""
        n = self.__class__.__name__
        return n[0] + "".join(" " + c if c.isupper() else c for c in n[1:])

    @abstractmethod
    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the LLM.

        All subclasses must implement this method. This method is responsible
        for extracting and validating records from a single string of text,
        which must be returned as a ParsedResponse object.

        Args:
            text: Text generated by the LLM.

        Returns:
            Parsed response object that contains the extracted records.
        """
        ...

    def __call__(self, prompt_number: int, text: str) -> ParsedResponse:
        """Parse a single LLM response into validated records.

        Sanitizes the text to valid UTF-8, delegates to the subclass
        ``_process_text_generation`` implementation, and tags the result
        with ``prompt_number``.

        Args:
            prompt_number: Index of the prompt within the current batch.
            text: Raw text generated by the fine-tuned model.

        Returns:
            Parsed response containing valid records, invalid records,
            and error tuples.
        """
        # Make sure the string composed of valid utf-8 characters.
        text = text.encode("utf-8", "ignore").decode("utf-8")

        # Call the processor-specific method to process the text.
        response = self._process_text_generation(text)
        response.prompt_number = prompt_number

        return response


class TabularDataProcessor(Processor):
    """Processor for standard (non-grouped, non-time-series) tabular data."""

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Extract and validate records from a flat JSONL string.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response with validated records and error details.
        """
        valid, invalid, errors = extract_and_validate_records(text, self.schema)
        return ParsedResponse(valid_records=valid, invalid_records=invalid, errors=errors)


class TimeSeriesDataProcessor(Processor):
    """Processor for time-series data generation tasks.

    Validates chronological ordering and timestamp intervals in
    addition to the standard schema checks.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters.
        time_column: Name of the timestamp column.
        interval_seconds: Expected interval between consecutive
            timestamps, or ``None`` if intervals vary.
        time_format: Timestamp format string (``strptime``), or
            ``"elapsed_seconds"`` for numeric elapsed time.

    Raises:
        ValueError: If ``time_column`` or ``time_format`` is ``None``.
    """

    def __init__(
        self,
        schema: dict,
        config: ValidationParameters,
        time_column: str | None,
        interval_seconds: int | None,
        time_format: str | None,
    ):
        super().__init__(schema=schema, config=config)
        if time_column is None:
            raise ValueError(
                "time_column is required for TimeSeriesDataProcessor but was None. "
                "Ensure config.time_series.timestamp_column is set."
            )
        if time_format is None:
            raise ValueError(
                "time_format is required for TimeSeriesDataProcessor but was None. "
                "This should have been inferred during training preprocessing. "
                "Check that process_timeseries_data() was called during training and "
                "that the inferred timestamp_format was saved to the config."
            )
        self.time_column: str = time_column
        self.interval_seconds = interval_seconds
        self.time_format: str = time_format

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Extract, validate, and check temporal ordering of time-series records.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response with validated records and error details.
        """
        valid, invalid, errors = extract_and_validate_timeseries_records(
            text, self.schema, self.time_column, self.interval_seconds, self.time_format
        )
        return ParsedResponse(valid_records=valid, invalid_records=invalid, errors=errors)


class GroupedDataProcessor(Processor):
    """Processor for grouped data generation tasks.

    Used when training examples are grouped (and optionally ordered) by
    one or more columns.  Validates that each group has a unique
    ``group_by`` value and respects the ``order_by`` ordering.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters controlling tolerance for
            invalid records, non-unique group values, etc.
        bos_token: Token delimiting the beginning of a group sequence.
        eos_token: Token delimiting the end of a group sequence.
        group_by: Column name that defines groups.
        order_by: Column name to enforce ordering within a group, or
            ``None`` if ordering is not required.
    """

    def __init__(
        self,
        schema: dict,
        config: ValidationParameters,
        bos_token: str,
        eos_token: str,
        group_by: str | None,
        order_by: str | None = None,
    ):
        super().__init__(schema=schema, config=config)
        if isinstance(group_by, str):
            group_by = [group_by]
        self.group_by = group_by
        self.order_by = order_by
        self.bos_token = bos_token
        self.eos_token = eos_token

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the fine-tuned model.

        For records to be valid, they should:
            - Be in a group that is bound by BOS and EOS tokens.
            - Respect the known JSONL schema.
            - Have a unique value for the `group_by` field(s).
            - Be ordered by the `order_by` field if specified.

        These requirements may be relaxed and automatically fixed depending on
        the settings in self.config.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response object that contains the extracted records.
        """
        groups = extract_groups_from_jsonl_string(text, self.bos_token, self.eos_token)
        groupby_validator = "groupby"

        if len(groups) == 0 and self.config.group_by_accept_no_delineator:
            groups = [text]

        if len(groups) == 0:
            return ParsedResponse(
                valid_records=[],
                invalid_records=[text],
                errors=[("Group BOS and/or EOS tokens missing", groupby_validator)],
            )

        valid_groups, invalid_groups, errors_groups = [], [], []

        for group in groups:
            valid, invalid, errors = extract_and_validate_records(group, self.schema)
            valid_with_str_members = [str(item) for item in valid]

            if len(valid) == 0:
                invalid_groups.extend(invalid)
                errors_groups.extend(errors)
                continue

            # Handle invalid records in the group (optionally ignore and proceed).
            if len(invalid) > 0:
                if self.config.group_by_ignore_invalid_records:
                    invalid = []
                    errors = []
                else:
                    # If there are any invalid records, the entire group is invalid.
                    invalid = valid_with_str_members + invalid
                    errors = errors + [("Invalid JSON in other groupby records", groupby_validator)] * len(valid)
                    valid = []
                    valid_groups.extend(valid)
                    invalid_groups.extend(invalid)
                    errors_groups.extend(errors)
                    continue

            # Handle non-unique group_by values (optionally fix by using first record's values).
            if len(set(tuple(record[gb] for gb in self.group_by) for record in valid)) != 1:
                if self.config.group_by_fix_non_unique_value:
                    for group_by in self.group_by:
                        for record in valid[1:]:
                            record[group_by] = valid[0][group_by]
                else:
                    # The group is invalid if the set of group_by fields is not unique.
                    valid, invalid = [], valid_with_str_members + invalid
                    errors = [("Groupby value is not unique", groupby_validator)] * len(invalid)
                    valid_groups.extend(valid)
                    invalid_groups.extend(invalid)
                    errors_groups.extend(errors)
                    continue

            # Handle unordered records when order_by is set (optionally fix by sorting).
            if self.order_by is not None and not check_if_records_are_ordered(valid, self.order_by):
                if self.config.group_by_fix_unordered_records:
                    valid.sort(key=lambda x: x[self.order_by])
                else:
                    # If order_by is specified, the group is invalid if the records are not ordered.
                    valid, invalid = [], valid_with_str_members + invalid
                    errors = [("Group not ordered", groupby_validator)] * len(invalid)
                    valid_groups.extend(valid)
                    invalid_groups.extend(invalid)
                    errors_groups.extend(errors)
                    continue

            valid_groups.extend(valid)
            invalid_groups.extend(invalid)
            errors_groups.extend(errors)

        return ParsedResponse(
            valid_records=valid_groups,
            invalid_records=invalid_groups,
            errors=errors_groups,
        )


def create_processor(schema: dict, metadata: ModelMetadata, config: SafeSynthesizerParameters) -> Processor:
    """Create the appropriate record processor for the current pipeline mode.

    Selects ``TimeSeriesDataProcessor``, ``GroupedDataProcessor``, or
    ``TabularDataProcessor`` based on the pipeline configuration.

    Args:
        schema: JSON schema describing the expected record format.
        metadata: Model metadata (prompt template, BOS/EOS tokens, etc.).
        config: Pipeline configuration determining the generation mode.

    Returns:
        Processor instance matching the configured generation mode.
    """
    if config.time_series.is_timeseries:
        processor = TimeSeriesDataProcessor(
            schema,
            config=config.generation.validation,
            time_column=config.time_series.timestamp_column,
            interval_seconds=config.time_series.timestamp_interval_seconds,
            time_format=config.time_series.timestamp_format,
        )
    elif config.data.group_training_examples_by:
        processor = GroupedDataProcessor(
            schema,
            config=config.generation.validation,
            group_by=config.data.group_training_examples_by,
            order_by=config.data.order_training_examples_by,
            bos_token=metadata.prompt_config.bos_token,
            eos_token=metadata.prompt_config.eos_token,
        )
    else:
        processor = TabularDataProcessor(schema, config=config.generation.validation)

    logger.info(f"Initialized the {processor.name}")
    return processor
