# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Feature Request
description: Request a new feature
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      placeholder: "Ex: I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: Alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Any other context or screenshots.
